project:
  type: website
  output-dir: docs

website:
  title: "Data Stories"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/dhanorkartushar2au-lgtm
format:
  html:
    theme: cosmo
    css: styles.css
